#!/usr/bin/env bash
#word2vec models closure files
python3 closure_words_from_model_with_translater.py  --vocab_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/spanish/spanish_crawl_w2v_line_sg_hs_1_w_5_v_400_i_50_1_may_18.vocab --vectors_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/spanish/spanish_crawl_w2v_line_sg_hs_1_w_5_v_400_i_50_1_may_18.vec  --input_file /home/vivek/ML_Sep_2017/WordVectorTraining/closurewords/spanish_closure/spanish_frequent_words.txt
python3 closure_words_from_model_with_translater.py  --vocab_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/albania/albania_crawl_w2v_line_sg_hs_1_w_5_v_400_i_50_1_may_18.vocab --vectors_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/albania/albania_crawl_w2v_line_sg_hs_1_w_5_v_400_i_50_1_may_18.vec  --input_file /home/vivek/ML_Sep_2017/WordVectorTraining/closurewords/albanian_closure/albanian_frequent_words.txt
python3 closure_words_from_model_with_translater.py  --vocab_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/french/french_crawl_w2v_line_sg_hs_1_w_5_v_400_i_5_16_april_18.vocab --vectors_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/french/french_crawl_w2v_line_sg_hs_1_w_5_v_400_i_5_16_april_18.vec  --input_file /home/vivek/ML_Sep_2017/WordVectorTraining/closurewords/french_closure/french_frequent_words.txt
python3 closure_words_from_model_with_translater.py  --vocab_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/german/german_w2v_sg_v_400_line_sentence_17_apr_18.vocab --vectors_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/german/german_w2v_sg_v_400_line_sentence_17_apr_18.vec  --input_file /home/vivek/ML_Sep_2017/WordVectorTraining/closurewords/german_closure/german_frequent_words.txt
python3 closure_words_from_model_with_translater.py  --vocab_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/english/english_wiki8__w2v_line_sg_hs_1_w_5_v_400_i_50_16_may_18.vocab --vectors_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/english/english_wiki8__w2v_line_sg_hs_1_w_5_v_400_i_50_16_may_18.vec  --input_file /home/vivek/ML_Sep_2017/WordVectorTraining/closurewords/english_closure/english_frequent_words.txt
python3 closure_words_from_model_with_translater.py  --vocab_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/urdu/urdu_update_w2v_500_12_feb_18.vocab --vectors_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/urdu/urdu_update_w2v_500_12_feb_18.vec  --input_file /home/vivek/ML_Sep_2017/WordVectorTraining/closurewords/arabic_closure/arabic_frequent_words.txt
python3 closure_words_from_model_with_translater.py  --vocab_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/arabic/arabic_w2v_500_21_Feb_18.vocab --vectors_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/arabic/arabic_w2v_500_21_Feb_18.vec  --input_file /home/vivek/ML_Sep_2017/WordVectorTraining/closurewords/urdu_closure/urdu_frequent_words.txt
python3 closure_words_from_model_with_translater.py  --vocab_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/car_model/car_crawl_w2v_line_sg_hs_1_w_5_v_400_i_50_18_may_18.vocab --vectors_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/Word2Vec/car_model/car_crawl_w2v_line_sg_hs_1_w_5_v_400_i_50_18_may_18.vec  --input_file /home/vivek/ML_Sep_2017/WordVectorTraining/closurewords/car_closure/car_frequent_words.txt



#glove models closure files
python3 closure_words_from_model_with_translater.py  --vocab_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/GloveModel/swedish/swedish_glove_500_05_feb_18.vocab --vectors_file /home/vivek/ML_Sep_2017/WordEmbeddingModels/GloveModel/swedish/swedish_glove_500_05_feb_18.vec  --input_file /home/vivek/ML_Sep_2017/WordVectorTraining/closurewords/swedish_closure/swedish_frequent_words.txt
exit